approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@testing-library/vue@*":
    dependencies:
      "@vue/compiler-dom": ^3.5.35
      "@vue/server-renderer": ^3.5.35
