import type { WorkspaceCommandName } from "./contracts";

export type WorkspaceCommandDomain = "workspace" | "github" | "repo" | "bulk" | "system";

export type WorkspaceCommandManifestEntry<TCommand extends WorkspaceCommandName = WorkspaceCommandName> = {
  command: TCommand;
  domain: WorkspaceCommandDomain;
};

export const WORKSPACE_COMMAND_GROUPS = {
  workspace: [
    "workspace_get_settings",
    "workspace_read_startup_cache",
    "workspace_clear_startup_cache",
    "workspace_write_startup_contributions",
    "workspace_set_root",
    "workspace_update_account_preferences",
    "workspace_set_contribution_identities",
    "workspace_scan_contribution_identities",
    "repo_set_preference",
    "repo_set_auto_sync",
    "workspace_pick_root",
    "workspace_pick_repo",
    "workspace_pick_files",
    "workspace_refresh_repos",
    "workspace_list_managed_repos",
    "workspace_scan_repos",
    "workspace_discover_repos",
    "workspace_add_repo",
    "workspace_create_local_repo",
    "workspace_clone_repo",
    "workspace_hide_repo",
    "workspace_reconcile_organization_repo_groups",
    "workspace_create_repo_group",
    "workspace_rename_repo_group",
    "workspace_delete_repo_group",
    "workspace_move_repo_to_group",
    "workspace_set_local_repo_favorite",
    "workspace_delete_local_repo",
    "workspace_remember_remote_repo",
    "workspace_set_remote_repo_favorite",
    "workspace_forget_remote_repo",
    "workspace_unhide_repo",
    "workspace_list_hidden_repos",
    "workspace_list_tasks",
    "workspace_cancel_task",
    "workspace_set_active_repo",
    "workspace_record_recent_local_repo",
    "workspace_set_refresh_paused",
    "workspace_enqueue_repo_refresh",
  ],
  github: [
    "github_get_binding_status",
    "github_start_device_flow",
    "github_poll_device_flow",
    "github_unbind",
    "github_get_account_profile",
    "github_get_account_readme",
    "github_update_account_profile",
    "github_get_organization_profile",
    "github_get_organization_overview",
    "github_list_repos",
    "github_list_watched_repos",
    "github_get_repo_subscription",
    "github_update_repo_subscription",
    "github_list_account_issues",
    "github_list_assigned_work",
    "github_list_notifications",
    "github_mark_notifications_read",
    "github_unsubscribe_notification",
    "github_list_action_notifications",
    "github_list_repo_contribution",
    "github_list_repo_owners",
    "github_list_repo_templates",
    "github_create_repo",
    "github_get_repo_management",
    "github_discovery_get_repository_status",
    "github_discovery_scan",
    "github_discovery_submit_pull_request_review",
    "github_update_repo_settings",
    "github_get_repo_settings_section",
    "github_update_repo_actions_permissions",
    "github_update_repo_workflow_permissions",
    "github_delete_repo",
    "github_list_branches",
    "github_get_branch_protection",
    "github_update_branch_protection",
    "github_list_repo_rulesets",
    "github_get_repo_ruleset",
    "github_update_repo_ruleset",
    "github_delete_branch",
    "github_list_pull_requests",
    "github_get_pull_request",
    "github_get_pull_request_discussion",
    "github_create_pull_request",
    "github_update_pull_request",
    "github_merge_pull_request",
    "github_list_pull_request_checks",
    "github_get_pull_request_code_review",
    "github_create_pull_request_line_comment",
    "github_reply_pull_request_review_thread",
    "github_submit_pull_request_code_review",
    "github_list_repo_files",
    "github_get_repo_file_preview",
    "github_list_issues",
    "github_get_issue_discussion",
    "github_get_issue_filter_metadata",
    "github_list_issue_labels",
    "github_list_issue_assignees",
    "github_create_issue",
    "github_update_issue",
    "github_get_discussion_metadata",
    "github_list_discussions",
    "github_get_discussion",
    "github_list_discussion_comments",
    "github_list_discussion_comment_replies",
    "github_create_discussion",
    "github_create_discussion_comment",
    "github_update_discussion_comment",
    "github_delete_discussion_comment",
    "github_update_discussion_reaction",
    "github_update_discussion_state",
    "github_update_discussion_answer",
    "github_create_issue_comment",
    "github_update_issue_comment",
    "github_delete_issue_comment",
    "github_add_issue_comment_reaction",
    "github_list_workflow_runs",
    "github_get_workflow_run_detail",
    "github_get_workflow_job_log",
    "github_rerun_failed_workflow_run",
    "github_rerun_workflow_job",
    "github_list_workflow_artifact_files",
    "github_get_workflow_artifact_file_preview",
    "github_list_repo_commits",
    "github_get_repo_commit_detail",
    "github_list_releases",
    "github_create_release",
    "github_update_release",
    "github_delete_release",
    "github_upload_release_asset",
    "github_attach_workflow_artifact_asset",
    "github_delete_release_asset",
  ],
  repo: [
    "repo_get_summary",
    "repo_get_storage_stats",
    "repo_refresh_summary",
    "repo_refresh_language_stats",
    "repo_list_files",
    "repo_get_file_preview",
    "repo_delete_file",
    "repo_get_changes",
    "repo_get_history",
    "repo_get_commit_detail",
    "repo_get_branches",
    "repo_get_conflicts",
    "repo_get_detail",
    "repo_get_remote_sync_config",
    "repo_set_remote_sync_policy",
    "repo_refresh_detail_patch",
    "repo_get_launch_config",
    "repo_list_launch_candidates",
    "repo_save_launch_config",
    "repo_get_launch_status",
    "repo_get_launch_logs",
    "repo_list_launch_history",
    "repo_start_launch",
    "repo_stop_launch",
    "repo_stage_files",
    "repo_unstage_files",
    "repo_discard_files",
    "repo_add_files_to_gitignore",
    "repo_commit",
    "repo_pull",
    "repo_merge_pull",
    "repo_fetch",
    "repo_start_rebase",
    "repo_push",
    "repo_push_new_branch",
    "repo_push_with_system_git",
    "repo_use_default_token_auth",
    "repo_checkout_branch",
    "repo_create_branch",
    "repo_rename_branch",
    "repo_merge_branch",
    "repo_delete_branch",
    "repo_set_upstream",
    "repo_list_stashes",
    "repo_get_stash_detail",
    "repo_stash_save",
    "repo_stash_apply",
    "repo_stash_pop",
    "repo_stash_drop",
    "repo_list_remotes",
    "repo_cherry_pick_commit",
    "repo_revert_commit",
    "repo_reset_to_commit",
    "repo_accept_conflict_file",
    "repo_resolve_conflict_file",
    "repo_mark_file_resolved",
    "repo_abort_conflict_operation",
    "repo_continue_conflict_operation",
  ],
  bulk: ["bulk_sync_preview", "bulk_sync_execute"],
  system: [
    "system_open_path",
    "system_open_path_target",
    "system_open_url",
    "lilia_code_create_task_handoff",
    "lilia_code_get_task_handoff_status",
    "lilia_code_open_task_handoff_result",
  ],
} as const satisfies Record<WorkspaceCommandDomain, readonly WorkspaceCommandName[]>;

type GroupedWorkspaceCommandName =
  (typeof WORKSPACE_COMMAND_GROUPS)[keyof typeof WORKSPACE_COMMAND_GROUPS][number];
type AssertNever<T extends never> = T;
export type WorkspaceCommandGroupCoverage = [
  AssertNever<Exclude<WorkspaceCommandName, GroupedWorkspaceCommandName>>,
  AssertNever<Exclude<GroupedWorkspaceCommandName, WorkspaceCommandName>>,
];

export const WORKSPACE_COMMAND_MANIFEST = Object.fromEntries(
  Object.entries(WORKSPACE_COMMAND_GROUPS).flatMap(([domain, commands]) =>
    commands.map((command) => [
      command,
      { command, domain: domain as WorkspaceCommandDomain },
    ]),
  ),
) as {
  [TCommand in WorkspaceCommandName]: WorkspaceCommandManifestEntry<TCommand>;
};
