use lilia_github_contracts::workspace::*;

delegate_command!(github; fn github_get_binding_status(app: AppHandle) -> Result<GitHubBindingStatus, String>);
delegate_command!(async github; fn github_start_device_flow() -> Result<GitHubDeviceFlowStart, String>);
delegate_command!(async github; fn github_poll_device_flow(app: AppHandle, device_code: String, interval_seconds: Option<i64>,) -> Result<GitHubDeviceFlowPollResult, String>);
delegate_command!(github; fn github_unbind(app: AppHandle) -> Result<(), String>);
delegate_command!(async github; fn github_list_repos(app: AppHandle, page: Option<u32>,) -> Result<GitHubRepoPage, String>);
delegate_command!(async github; fn github_list_repo_owners(app: AppHandle) -> Result<Vec<GitHubRepoOwner>, String>);
delegate_command!(async github; fn github_create_repo(app: AppHandle, request: GitHubCreateRepoRequest,) -> Result<GitHubRepoSummary, String>);
delegate_command!(async github; fn github_get_repo_management(app: AppHandle, repo_full_name: String, force_refresh: Option<bool>,) -> Result<GitHubRepoManagement, String>);
delegate_command!(async github; fn github_update_repo_settings(app: AppHandle, repo_full_name: String, request: GitHubUpdateRepoSettingsRequest,) -> Result<GitHubRepoManagement, String>);
delegate_command!(async github; fn github_get_repo_settings_section(app: AppHandle, repo_full_name: String, section: String, force_refresh: Option<bool>,) -> Result<GitHubRepoSettingsSection, String>);
delegate_command!(async github; fn github_update_repo_actions_permissions(app: AppHandle, repo_full_name: String, request: GitHubRepoActionsPermissionsRequest,) -> Result<(), String>);
delegate_command!(async github; fn github_update_repo_workflow_permissions(app: AppHandle, repo_full_name: String, request: GitHubRepoWorkflowPermissionsRequest,) -> Result<(), String>);
delegate_command!(async github; fn github_delete_repo(app: AppHandle, repo_full_name: String) -> Result<(), String>);
delegate_command!(async github; fn github_list_branches(app: AppHandle, repo_full_name: String,) -> Result<Vec<BranchSummary>, String>);
delegate_command!(async github; fn github_delete_branch(app: AppHandle, repo_full_name: String, branch_name: String,) -> Result<(), String>);
delegate_command!(async github; fn github_list_pull_requests(app: AppHandle, repo_full_name: String, state: Option<String>, per_page: Option<u32>, sort: Option<String>, direction: Option<String>, creator: Option<String>, assignee: Option<String>, labels: Option<Vec<String>>, milestone: Option<serde_json::Value>, project: Option<String>, review: Option<String>, query: Option<String>, force_refresh: Option<bool>,) -> Result<Vec<GitHubPullRequest>, String>);
delegate_command!(async github; fn github_get_pull_request(app: AppHandle, repo_full_name: String, pull_number: u64,) -> Result<GitHubPullRequest, String>);
delegate_command!(async github; fn github_get_pull_request_discussion(app: AppHandle, repo_full_name: String, pull_number: u64, force_refresh: Option<bool>,) -> Result<GitHubPullRequestDiscussion, String>);
delegate_command!(async github; fn github_create_pull_request(app: AppHandle, repo_full_name: String, request: GitHubCreatePullRequestRequest,) -> Result<GitHubPullRequest, String>);
delegate_command!(async github; fn github_update_pull_request(app: AppHandle, repo_full_name: String, pull_number: u64, request: GitHubUpdatePullRequestRequest,) -> Result<GitHubPullRequest, String>);
delegate_command!(async github; fn github_merge_pull_request(app: AppHandle, repo_full_name: String, pull_number: u64, request: GitHubMergePullRequestRequest,) -> Result<GitHubPullRequest, String>);
delegate_command!(async github; fn github_list_pull_request_checks(app: AppHandle, repo_full_name: String, pull_number: u64, force_refresh: Option<bool>,) -> Result<Vec<GitHubPullRequestCheck>, String>);
delegate_command!(async github; fn github_list_issues(app: AppHandle, repo_full_name: String, state: Option<String>, per_page: Option<u32>, sort: Option<String>, direction: Option<String>, since: Option<String>, creator: Option<String>, assignee: Option<String>, labels: Option<Vec<String>>, milestone: Option<serde_json::Value>, project: Option<String>, query: Option<String>, force_refresh: Option<bool>,) -> Result<Vec<GitHubIssue>, String>);
delegate_command!(async github; fn github_get_issue_discussion(app: AppHandle, repo_full_name: String, issue_number: u64, force_refresh: Option<bool>,) -> Result<GitHubIssueDiscussion, String>);
delegate_command!(async github; fn github_get_issue_filter_metadata(app: AppHandle, repo_full_name: String, force_refresh: Option<bool>,) -> Result<GitHubIssueFilterMetadata, String>);
delegate_command!(async github; fn github_list_issue_labels(app: AppHandle, repo_full_name: String, force_refresh: Option<bool>,) -> Result<Vec<String>, String>);
delegate_command!(async github; fn github_list_issue_assignees(app: AppHandle, repo_full_name: String, force_refresh: Option<bool>,) -> Result<Vec<String>, String>);
delegate_command!(async github; fn github_create_issue(app: AppHandle, repo_full_name: String, request: GitHubCreateIssueRequest,) -> Result<GitHubIssue, String>);
delegate_command!(async github; fn github_update_issue(app: AppHandle, repo_full_name: String, issue_number: u64, request: GitHubUpdateIssueRequest,) -> Result<GitHubIssue, String>);
delegate_command!(async github; fn github_list_workflow_runs(app: AppHandle, repo_full_name: String, per_page: Option<u32>, force_refresh: Option<bool>,) -> Result<Vec<GitHubWorkflowRun>, String>);
delegate_command!(async github; fn github_get_workflow_run_detail(app: AppHandle, repo_full_name: String, run_id: u64, _force_refresh: Option<bool>,) -> Result<GitHubWorkflowRunDetail, String>);
delegate_command!(async github; fn github_get_workflow_job_log(app: AppHandle, repo_full_name: String, job_id: u64, _force_refresh: Option<bool>,) -> Result<GitHubWorkflowJobLog, String>);
delegate_command!(async github; fn github_list_workflow_artifact_files(app: AppHandle, repo_full_name: String, artifact_id: u64,) -> Result<Vec<GitHubWorkflowArtifactEntry>, String>);
delegate_command!(async github; fn github_get_workflow_artifact_file_preview(app: AppHandle, repo_full_name: String, artifact_id: u64, path: String,) -> Result<RepoFilePreview, String>);
delegate_command!(async github; fn github_list_repo_commits(app: AppHandle, repo_full_name: String, per_page: Option<u32>, sha: Option<String>, force_refresh: Option<bool>,) -> Result<Vec<CommitSummary>, String>);
delegate_command!(async github; fn github_get_repo_commit_detail(app: AppHandle, repo_full_name: String, hash: String, force_refresh: Option<bool>,) -> Result<CommitDetail, String>);
delegate_command!(async github; fn github_list_releases(app: AppHandle, repo_full_name: String, force_refresh: Option<bool>,) -> Result<Vec<GitHubRelease>, String>);
delegate_command!(async github; fn github_create_release(app: AppHandle, repo_full_name: String, request: GitHubCreateReleaseRequest,) -> Result<GitHubRelease, String>);
delegate_command!(async github; fn github_update_release(app: AppHandle, repo_full_name: String, release_id: u64, request: GitHubUpdateReleaseRequest,) -> Result<GitHubRelease, String>);
delegate_command!(async github; fn github_delete_release(app: AppHandle, repo_full_name: String, release_id: u64,) -> Result<(), String>);
delegate_command!(async github; fn github_upload_release_asset(app: AppHandle, repo_full_name: String, release_id: u64, file_path: String, label: Option<String>,) -> Result<GitHubReleaseAsset, String>);
delegate_command!(async github; fn github_attach_workflow_artifact_asset(app: AppHandle, repo_full_name: String, request: GitHubAttachWorkflowArtifactAssetRequest,) -> Result<GitHubReleaseAsset, String>);
delegate_command!(async github; fn github_delete_release_asset(app: AppHandle, repo_full_name: String, release_id: u64, asset_id: u64,) -> Result<(), String>);
delegate_command!(async github; fn github_list_repo_files(app: AppHandle, repo_full_name: String, parent_path: Option<String>, ref_name: Option<String>, _force_refresh: Option<bool>,) -> Result<Vec<RepoFileTreeEntry>, String>);
delegate_command!(async github; fn github_get_repo_file_preview(app: AppHandle, repo_full_name: String, path: String, ref_name: Option<String>, _force_refresh: Option<bool>,) -> Result<RepoFilePreview, String>);
delegate_command!(async github; fn github_list_account_issues(app: AppHandle, state: Option<String>, per_page: Option<u32>, sort: Option<String>, direction: Option<String>, _force_refresh: Option<bool>,) -> Result<Vec<GitHubAccountIssueItem>, String>);
delegate_command!(async github; fn github_list_action_notifications(app: AppHandle, per_page: Option<u32>, _force_refresh: Option<bool>,) -> Result<Vec<GitHubActionNotification>, String>);
delegate_command!(async github; fn github_list_repo_contribution(app: AppHandle, repo_full_name: String,) -> Result<GitHubContributionResult, String>);
