use lilia_github_contracts::workspace::*;

delegate_command!(async repos; fn workspace_refresh_repos(app: AppHandle) -> Result<Vec<RepoSummary>, String>);
delegate_command!(async repos; fn workspace_list_managed_repos(app: AppHandle) -> Result<Vec<RepoSummary>, String>);
delegate_command!(async repos; fn workspace_scan_repos(app: AppHandle) -> Result<Vec<RepoSummary>, String>);
delegate_command!(async repos; fn workspace_discover_repos(app: AppHandle) -> Result<Vec<RepoSummary>, String>);
delegate_command!(async repos; fn workspace_add_repo(app: AppHandle, repo_path: String) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn workspace_create_local_repo(app: AppHandle, request: WorkspaceCreateLocalRepoRequest,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn workspace_clone_repo(app: AppHandle, request: WorkspaceCloneRepoRequest,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_get_summary(app: AppHandle, repo_id: String) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_refresh_summary(app: AppHandle, repo_id: String, options: Option<RepoRefreshSummaryOptions>,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_refresh_language_stats(app: AppHandle, repo_id: String,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_get_changes(app: AppHandle, repo_id: String) -> Result<Vec<RepoChange>, String>);
delegate_command!(async repos; fn repo_get_history(app: AppHandle, repo_id: String,) -> Result<Vec<CommitSummary>, String>);
delegate_command!(async repos; fn repo_get_commit_detail(app: AppHandle, repo_id: String, hash: String,) -> Result<CommitDetail, String>);
delegate_command!(async repos; fn repo_get_branches(app: AppHandle, repo_id: String,) -> Result<Vec<BranchSummary>, String>);
delegate_command!(async repos; fn repo_get_conflicts(app: AppHandle, repo_id: String,) -> Result<RepoConflictState, String>);
delegate_command!(async repos; fn repo_get_detail(app: AppHandle, repo_id: String) -> Result<RepoDetail, String>);
delegate_command!(async repos; fn repo_refresh_detail_patch(app: AppHandle, repo_id: String, request: RepoDetailPatchRequest,) -> Result<RepoDetailPatch, String>);
delegate_command!(async repos; fn repo_stage_files(app: AppHandle, repo_id: String, files: Vec<String>,) -> Result<(), String>);
delegate_command!(async repos; fn repo_unstage_files(app: AppHandle, repo_id: String, files: Vec<String>,) -> Result<(), String>);
delegate_command!(async repos; fn repo_discard_files(app: AppHandle, repo_id: String, files: Vec<String>,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_add_files_to_gitignore(app: AppHandle, repo_id: String, files: Vec<String>,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_commit(app: AppHandle, repo_id: String, files: Vec<String>, message: String, push_after: bool,) -> Result<RepoCommitResult, String>);
delegate_command!(async repos; fn repo_pull(app: AppHandle, repo_id: String, local_changes_mode: Option<RepoPullLocalChangesMode>,) -> Result<RepoSyncOperationResult, String>);
delegate_command!(async repos; fn repo_merge_pull(app: AppHandle, repo_id: String, local_changes_mode: Option<RepoPullLocalChangesMode>,) -> Result<RepoSyncOperationResult, String>);
delegate_command!(async repos; fn repo_fetch(app: AppHandle, repo_id: String) -> Result<RepoSyncOperationResult, String>);
delegate_command!(async repos; fn repo_start_rebase(app: AppHandle, repo_id: String, onto_ref: Option<String>, local_changes_mode: Option<RepoPullLocalChangesMode>,) -> Result<RepoOperationResult, String>);
delegate_command!(async repos; fn repo_push(app: AppHandle, repo_id: String, remote_names: Option<Vec<String>>,) -> Result<RepoSyncOperationResult, String>);
delegate_command!(async repos; fn repo_push_new_branch(app: AppHandle, repo_id: String, remote_names: Option<Vec<String>>, branch_name: Option<String>,) -> Result<RepoSyncOperationResult, String>);
delegate_command!(async repos; fn repo_push_with_system_git(app: AppHandle, repo_id: String, remote_names: Option<Vec<String>>,) -> Result<RepoSyncOperationResult, String>);
delegate_command!(async repos; fn repo_checkout_branch(app: AppHandle, repo_id: String, branch: String,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_create_branch(app: AppHandle, repo_id: String, name: String, from_ref: String, checkout_after: bool,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_rename_branch(app: AppHandle, repo_id: String, old_name: String, new_name: String,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_merge_branch(app: AppHandle, repo_id: String, branch: String,) -> Result<RepoMergePullResult, String>);
delegate_command!(async repos; fn repo_delete_branch(app: AppHandle, repo_id: String, branch: String,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_set_upstream(app: AppHandle, repo_id: String, branch: String, upstream: String,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_list_stashes(app: AppHandle, repo_id: String,) -> Result<Vec<RepoStashEntry>, String>);
delegate_command!(async repos; fn repo_get_stash_detail(app: AppHandle, repo_id: String, stash_id: String,) -> Result<RepoStashDetail, String>);
delegate_command!(async repos; fn repo_stash_save(app: AppHandle, repo_id: String, message: Option<String>,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_stash_apply(app: AppHandle, repo_id: String, stash_id: String,) -> Result<RepoOperationResult, String>);
delegate_command!(async repos; fn repo_stash_pop(app: AppHandle, repo_id: String, stash_id: String,) -> Result<RepoOperationResult, String>);
delegate_command!(async repos; fn repo_stash_drop(app: AppHandle, repo_id: String, stash_id: String,) -> Result<Vec<RepoStashEntry>, String>);
delegate_command!(async repos; fn repo_list_remotes(app: AppHandle, repo_id: String) -> Result<Vec<RepoRemote>, String>);
delegate_command!(async repos; fn repo_cherry_pick_commit(app: AppHandle, repo_id: String, hash: String,) -> Result<RepoOperationResult, String>);
delegate_command!(async repos; fn repo_revert_commit(app: AppHandle, repo_id: String, hash: String,) -> Result<RepoOperationResult, String>);
delegate_command!(async repos; fn repo_reset_to_commit(app: AppHandle, repo_id: String, hash: String, mode: Option<String>,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_accept_conflict_file(app: AppHandle, repo_id: String, path: String, side: String, stage: bool,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_resolve_conflict_file(app: AppHandle, repo_id: String, path: String, choices: Vec<RepoConflictChoice>, stage: bool,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_mark_file_resolved(app: AppHandle, repo_id: String, path: String,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_abort_conflict_operation(app: AppHandle, repo_id: String,) -> Result<RepoSummary, String>);
delegate_command!(async repos; fn repo_continue_conflict_operation(app: AppHandle, repo_id: String,) -> Result<RepoSummary, String>);
