use lilia_github_contracts::workspace::*;

delegate_command!(settings; fn workspace_get_settings(app: AppHandle) -> WorkspaceSettings);
delegate_command!(settings; fn workspace_get_bootstrap(app: AppHandle) -> WorkspaceBootstrap);
delegate_command!(settings; fn workspace_create(app: AppHandle, name: String, root_path: String,) -> Result<WorkspaceBootstrap, String>);
delegate_command!(settings; fn workspace_rename(app: AppHandle, workspace_id: String, name: String,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_update_recent_context(app: AppHandle, workspace_id: String, context: Option<WorkspaceRecentContextV1>,) -> Result<(), String>);
delegate_command!(settings; fn workspace_delete(app: AppHandle, workspace_id: String,) -> Result<WorkspaceBootstrap, String>);
delegate_command!(settings; fn workspace_switch(app: AppHandle, workspace_id: String,) -> Result<WorkspaceBootstrap, String>);
delegate_command!(settings; fn workspace_add_root(app: AppHandle, workspace_id: String, root_path: String,) -> Result<WorkspaceBootstrap, String>);
delegate_command!(settings; fn workspace_remove_root(app: AppHandle, workspace_id: String, root_id: String,) -> Result<WorkspaceBootstrap, String>);
delegate_command!(settings; fn workspace_set_primary_root(app: AppHandle, workspace_id: String, root_id: String,) -> Result<WorkspaceBootstrap, String>);
delegate_command!(settings; fn workspace_update_view_preferences(app: AppHandle, preferences: WorkspaceViewPreferences,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_read_startup_cache(app: AppHandle) -> Option<WorkspaceStartupCache>);
delegate_command!(settings; fn workspace_clear_startup_cache(app: AppHandle) -> Result<(), String>);
delegate_command!(settings; fn workspace_write_startup_contributions(app: AppHandle, contributions: WorkspaceStartupContributions,) -> Result<WorkspaceStartupCache, String>);
delegate_command!(settings; fn workspace_update_account_preferences(app: AppHandle, preferences: AccountPreferences,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_set_contribution_identities(app: AppHandle, identities: Vec<ContributionIdentity>,) -> Result<WorkspaceSettings, String>);
delegate_command!(async settings; fn workspace_scan_contribution_identities(app: AppHandle) -> Result<ContributionIdentityRecommendationResult, String>);
delegate_command!(settings; fn repo_set_preference(app: AppHandle, repo_id: String, key: String, value: bool,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn repo_set_auto_sync(app: AppHandle, repo_id: String, auto_sync: bool,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn repo_get_remote_sync_config(app: AppHandle, repo_id: String,) -> Result<RepoRemoteSyncConfig, String>);
delegate_command!(settings; fn repo_set_remote_sync_policy(app: AppHandle, repo_id: String, policy: RepoRemoteSyncPolicy,) -> Result<RepoRemoteSyncConfig, String>);
delegate_dialog_command!(settings; fn workspace_pick_root(app: AppHandle) -> Result<Option<String>, String>);
delegate_dialog_command!(settings; fn workspace_pick_repo(app: AppHandle) -> Result<Option<String>, String>);
delegate_dialog_command!(settings; fn workspace_pick_files(app: AppHandle) -> Result<Vec<String>, String>);
delegate_command!(settings; fn workspace_hide_repo(app: AppHandle, repo_id: String) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_create_repo_group(app: AppHandle, name: String,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_rename_repo_group(app: AppHandle, group_id: String, name: String,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_delete_repo_group(app: AppHandle, group_id: String,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_move_repo_to_group(app: AppHandle, repo_id: String, group_id: Option<String>, path_mode: Option<WorkspaceRepoPathMode>,) -> Result<WorkspaceRepoRelocationResult, String>);
delegate_dialog_command!(settings; fn workspace_relocate_local_repo(app: AppHandle, repo_id: String, target_path: Option<String>,) -> Result<WorkspaceRepoRelocationResult, String>);
delegate_command!(settings; fn workspace_reconcile_organization_repo_groups(app: AppHandle, organization_logins: Vec<String>,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_set_local_repo_favorite(app: AppHandle, repo_id: String, favorite: bool,) -> Result<WorkspaceSettings, String>);
delegate_command!(async settings; fn workspace_delete_local_repo(app: AppHandle, repo_id: String,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_remember_remote_repo(app: AppHandle, repo: RemoteRepoShortcut,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_set_remote_repo_favorite(app: AppHandle, repo: RemoteRepoShortcut, favorite: bool,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_forget_remote_repo(app: AppHandle, full_name: String,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_unhide_repo(app: AppHandle, repo_id: String) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn repo_use_default_token_auth(app: AppHandle, repo_id: String,) -> Result<WorkspaceSettings, String>);
delegate_command!(settings; fn workspace_list_hidden_repos(app: AppHandle) -> Vec<HiddenRepo>);
delegate_command!(settings; fn workspace_record_recent_local_repo(app: AppHandle, repo_id: String,) -> Result<WorkspaceSettings, String>);
