import { readonly } from "vue";
import {
  authBindingStatusText,
  authPendingStatusText,
  authRemainingText,
  deviceFlow,
  githubBinding,
  isAuthorized,
  isReady,
  repoById,
  state,
  workspaceRoot,
} from "./workspace/state";
import {
  initialize,
  chooseWorkspaceRoot,
} from "./workspace/lifecycle";
import {
  startAuthFlow,
  pollAuthFlow,
} from "./workspace/auth";
import {
  abortConflictOperation,
  acceptConflictFile,
  checkout,
  cloneRepo,
  addLocalRepo,
  discoverRepos,
  commit,
  continueConflictOperation,
  refreshRepoStatusList,
  forgetRemoteRepo,
  hideRepo,
  listHiddenRepos,
  loadRepoDetail,
  markConflictFileResolved,
  mergePull,
  pull,
  push,
  pushWithSystemGit,
  refreshRepoContributions,
  refreshRepoLanguageStats,
  refreshLanguageStatsForRepos,
  rememberRemoteRepo,
  refreshRepos,
  resolveConflictFile,
  stage,
  unstage,
  unhideRepo,
} from "./workspace/repositories";
import {
  loadLaunch,
  refreshLaunchLogs,
  refreshLaunchStatus,
  saveLaunchConfig,
  startLaunch,
  stopLaunch,
} from "./workspace/launch";
import {
  closeBulkPreview,
  executeBulk,
  previewBulk,
  syncAll,
} from "./workspace/bulk";
import {
  openPath,
  openUrl,
} from "./workspace/system";

export function useWorkspace() {
  return {
    state: readonly(state),
    deviceFlow: readonly(deviceFlow),
    workspaceRoot,
    githubBinding,
    isAuthorized,
    isReady,
    authBindingStatusText,
    authPendingStatusText,
    authRemainingText,
    initialize,
    chooseWorkspaceRoot,
    cloneRepo,
    addLocalRepo,
    discoverRepos,
    refreshRepos,
    refreshRepoStatusList,
    refreshRepoContributions,
    refreshRepoLanguageStats,
    refreshLanguageStatsForRepos,
    rememberRemoteRepo,
    forgetRemoteRepo,
    hideRepo,
    unhideRepo,
    listHiddenRepos,
    startAuthFlow,
    pollAuthFlow,
    loadRepoDetail,
    loadLaunch,
    saveLaunchConfig,
    refreshLaunchStatus,
    refreshLaunchLogs,
    startLaunch,
    stopLaunch,
    stage,
    unstage,
    commit,
    pull,
    mergePull,
    push,
    pushWithSystemGit,
    checkout,
    acceptConflictFile,
    resolveConflictFile,
    markConflictFileResolved,
    abortConflictOperation,
    continueConflictOperation,
    previewBulk,
    executeBulk,
    syncAll,
    closeBulkPreview,
    repoById,
    openPath,
    openUrl,
  };
}
