import { readonly } from "vue";
import {
  authBindingStatusText,
  authPendingStatusText,
  authRemainingText,
  deviceFlow,
  githubBinding,
  isAuthorized,
  isReady,
  repoById,
  repoUsesSystemGit,
  state,
  workspaceRoot,
} from "./workspace/state";
import {
  initialize,
  chooseWorkspaceRoot,
  choosingWorkspaceRoot,
} from "./workspace/lifecycle";
import {
  startAuthFlow,
  pollAuthFlow,
  unbindGitHub,
} from "./workspace/auth";
import {
  abortConflictOperation,
  acceptConflictFile,
  checkout,
  cancelWorkspaceTask,
  cherryPickCommit,
  cloneRepo,
  createLocalRepo,
  createRepoGroup,
  createBranch,
  addLocalRepo,
  deleteRepoGroup,
  discoverRepos,
  commit,
  continueConflictOperation,
  deleteBranch,
  deleteRepoFile,
  addFilesToGitignore,
  applyStash,
  discardChanges,
  dropStash,
  requestRepoStatusRefresh,
  autoSyncRepoIfNeeded,
  forgetRemoteRepo,
  deleteLocalRepo,
  hideRepo,
  listHiddenRepos,
  listRemotes,
  getRemoteSyncConfig,
  listStashes,
  loadRepoDetail,
  clearRepoLocalCache,
  markConflictFileResolved,
  mergeBranch,
  mergePull,
  popStash,
  pull,
  push,
  pushNewBranch,
  pushWithSystemGit,
  resetToCommit,
  revertCommit,
  saveStash,
  setUpstream,
  startRebase,
  useDefaultTokenAuthForRepo,
  refreshRepoContributions,
  refreshRepoLanguageStats,
  refreshLanguageStatsForRepos,
  rememberRemoteRepo,
  setRepoAutoSync,
  setRepoSetting,
  setRemoteSyncPolicy,
  setContributionIdentities,
  scanContributionIdentities,
  moveRepoToGroup,
  renameRepoGroup,
  refreshRepos,
  renameBranch,
  resolveConflictFile,
  stage,
  unstage,
  unhideRepo,
} from "./workspace/repositories";
import {
  loadLaunch,
  refreshLaunchLogs,
  refreshLaunchHistory,
  refreshLaunchStatus,
  saveLaunchConfig,
  startLaunch,
  stopLaunch,
} from "./workspace/launch";
import {
  closeBulkPreview,
  executeBulk,
  previewBulk,
  syncAll,
} from "./workspace/bulk";
import {
  openPath,
  openPathTarget,
  openUrl,
  copyText,
} from "./workspace/system";
import {
  getAccountProfile,
  getAccountRepositoryOwners,
  getGitHubRepositorySubscription,
  listGitHubWatchedRepos,
  pickAccountWorkspaceRoot,
  reloadAccountWorkspace,
  updateAccountPreferences,
  updateAccountProfile,
  updateGitHubRepositorySubscription,
} from "./workspace/account";

export function useWorkspace() {
  return {
    state: readonly(state),
    deviceFlow: readonly(deviceFlow),
    workspaceRoot,
    githubBinding,
    isAuthorized,
    isReady,
    authBindingStatusText,
    authPendingStatusText,
    authRemainingText,
    initialize,
    chooseWorkspaceRoot,
    choosingWorkspaceRoot: readonly(choosingWorkspaceRoot),
    cancelWorkspaceTask,
    cloneRepo,
    createLocalRepo,
    createRepoGroup,
    addLocalRepo,
    deleteRepoGroup,
    discoverRepos,
    refreshRepos,
    requestRepoStatusRefresh,
    autoSyncRepoIfNeeded,
    refreshRepoContributions,
    refreshRepoLanguageStats,
    refreshLanguageStatsForRepos,
    rememberRemoteRepo,
    setRepoAutoSync,
    setRepoSetting,
    setContributionIdentities,
    scanContributionIdentities,
    moveRepoToGroup,
    renameRepoGroup,
    forgetRemoteRepo,
    deleteLocalRepo,
    hideRepo,
    unhideRepo,
    listHiddenRepos,
    startAuthFlow,
    pollAuthFlow,
    unbindGitHub,
    loadRepoDetail,
    clearRepoLocalCache,
    loadLaunch,
    saveLaunchConfig,
    refreshLaunchStatus,
    refreshLaunchLogs,
    refreshLaunchHistory,
    startLaunch,
    stopLaunch,
    stage,
    unstage,
    discardChanges,
    addFilesToGitignore,
    commit,
    createBranch,
    deleteBranch,
    deleteRepoFile,
    pull,
    mergeBranch,
    mergePull,
    startRebase,
    push,
    pushNewBranch,
    pushWithSystemGit,
    useDefaultTokenAuthForRepo,
    checkout,
    renameBranch,
    setUpstream,
    listStashes,
    saveStash,
    applyStash,
    popStash,
    dropStash,
    listRemotes,
    getRemoteSyncConfig,
    setRemoteSyncPolicy,
    cherryPickCommit,
    revertCommit,
    resetToCommit,
    acceptConflictFile,
    resolveConflictFile,
    markConflictFileResolved,
    abortConflictOperation,
    continueConflictOperation,
    previewBulk,
    executeBulk,
    syncAll,
    closeBulkPreview,
    repoById,
    repoUsesSystemGit,
    openPath,
    openPathTarget,
    openUrl,
    copyText,
    getAccountProfile,
    getAccountRepositoryOwners,
    listGitHubWatchedRepos,
    getGitHubRepositorySubscription,
    updateGitHubRepositorySubscription,
    updateAccountProfile,
    pickAccountWorkspaceRoot,
    updateAccountPreferences,
    reloadAccountWorkspace,
  };
}
